<h3 align='center'>Ensemble Learning: Bagging Tutorial Exercise Solution</h3>

1. Load heart disease dataset in pandas dataframe
1. Remove outliers using Z score, Usual guideline is to remove anything that has Z score > 3 formula or Z score < -3.
1. Apply scaling. 
1. Build a classification using SVM. Use standaloe model as well Bagging model and check if you see any difference in the performance.
1. Now use decision tree classifier. Use standalone model as well as Bagging and check if you notice any difference in performance.
1. comparing performance of svm and decision tree classifier figure out where is makes most sense to use bagging and why. Use internet to figure out in what conditions bagging works the best.

In [115]:
import pandas as pd

df = pd.read_csv(r"E:\1_Data_Science\Machine-Learning-Projects\32. Bagging\Exercise_Bagging_Heart_Disease_Prediction\heart.csv")

df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [116]:
df.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [117]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

#### Treat Outliers

In [118]:
df[df.Cholesterol>(df.Cholesterol.mean()+3*df.Cholesterol.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
76,32,M,ASY,118,529,0,Normal,130,N,0.0,Flat,1
149,54,M,ASY,130,603,1,Normal,125,Y,1.0,Flat,1
616,67,F,NAP,115,564,0,LVH,160,N,1.6,Flat,0

In [119]:
df.shape

(918, 12)

In [120]:
df1 = df[df.Cholesterol<=(df.Cholesterol.mean()+3*df.Cholesterol.std())]
df1.shape

(915, 12)

In [121]:
df[df.MaxHR>(df.MaxHR.mean()+3*df.MaxHR.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [122]:
df[df.FastingBS>(df.FastingBS.mean()+3*df.FastingBS.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [123]:
df[df.Oldpeak>(df.Oldpeak.mean()+3*df.Oldpeak.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
166,50,M,ASY,140,231,0,ST,140,Y,5.0,Flat,1
702,59,M,TA,178,270,0,LVH,145,N,4.2,Down,0
771,55,M,ASY,140,217,0,Normal,111,Y,5.6,Down,1
791,51,M,ASY,140,298,0,Normal,122,Y,4.2,Flat,1
850,62,F,ASY,160,164,0,LVH,145,N,6.2,Down,1
900,58,M,ASY,114,318,0,ST,140,N,4.4,Down,1

In [124]:
df2 = df1[df1.Oldpeak<=(df.Oldpeak.mean()+3*df.Oldpeak.std())]
df2.shape

(909, 12)

In [125]:
df[df.RestingBP>(df.RestingBP.mean()+3*df.RestingBP.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
109,39,M,ATA,190,241,0,Normal,106,N,0.0,Up,0
241,54,M,ASY,200,198,0,Normal,142,Y,2.0,Flat,1
365,64,F,ASY,200,0,0,Normal,140,Y,1.0,Flat,1
399,61,M,NAP,200,0,1,ST,70,N,0.0,Flat,1
592,61,M,ASY,190,287,1,LVH,150,Y,2.0,Down,1
732,56,F,ASY,200,288,1,LVH,133,Y,4.0,Down,1
759,54,M,ATA,192,283,0,LVH,195,N,0.0,Up,1

In [126]:
df3 = df2[df2.RestingBP<=(df2.RestingBP.mean()+3*df2.RestingBP.std())]
df3.shape

(902, 12)

In [127]:
df.ChestPainType.unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [128]:
df.RestingECG.unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [129]:
df.ExerciseAngina.unique()

array(['N', 'Y'], dtype=object)

In [130]:
df.ST_Slope.unique()

array(['Up', 'Flat', 'Down'], dtype=object)

#### Handle text columns using label encoding and one hot encoding

In [131]:
df4 = df3.copy()

df4 = df4.replace({
    'Exercise_Angina': {'N':0, 'Y':1},
    'ST_Slope': {'Down':1, 'Flat':2,'Up':3},
    'RestingECG': {'Normal':1, 'ST':2, 'LVH':3}
})

df4 = df4.infer_objects(copy=False)

C:\Users\Hi\AppData\Local\Temp\ipykernel_17688\2673692683.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df4 = df4.replace({

In [133]:
df4.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,1,172,N,0.0,3,0
1,49,F,NAP,160,180,0,1,156,N,1.0,2,1
2,37,M,ATA,130,283,0,2,98,N,0.0,3,0
3,48,F,ASY,138,214,0,1,108,Y,1.5,2,1
4,54,M,NAP,150,195,0,1,122,N,0.0,3,0

In [114]:
df5 = pd.get_dummies(df4, drop_first=True, dtype=int)
df5.head()

,Age,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,Oldpeak,ST_Slope,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,ExerciseAngina_Y
0,40,140,289,0,1,172,0.0,3,0,1,1,0,0,0
1,49,160,180,0,1,156,1.0,2,1,0,0,1,0,0
2,37,130,283,0,2,98,0.0,3,0,1,1,0,0,0
3,48,138,214,0,1,108,1.5,2,1,0,0,0,0,1
4,54,150,195,0,1,122,0.0,3,0,1,0,1,0,0

When Should You Use drop_first=True?

1. ✔ Yes → When using Linear / Logistic Regression
1. ❌ No → When using Tree models (Random Forest, XGBoost)

Interview-Level Explanation

If asked:
Why drop_first=True?

You answer:

To prevent multicollinearity caused by redundant dummy variables, especially when using linear models.

That’s the correct reasoning.

Train Test Split

In [134]:
X = df5.drop("HeartDisease", axis='columns')
y = df5.HeartDisease

X.head()

,Age,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,Oldpeak,ST_Slope,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,ExerciseAngina_Y
0,40,140,289,0,1,172,0.0,3,1,1,0,0,0
1,49,160,180,0,1,156,1.0,2,0,0,1,0,0
2,37,130,283,0,2,98,0.0,3,1,1,0,0,0
3,48,138,214,0,1,108,1.5,2,0,0,0,0,1
4,54,150,195,0,1,122,0.0,3,1,0,1,0,0

In [136]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled[:3]

array([[-1.42896269,  0.46089071,  0.85238015, -0.55087949, -0.74461081,
         1.38191324, -0.84676261,  1.0456339 ,  0.51485643,  2.06757196,
        -0.53547478, -0.22914788, -0.82065181],
       [-0.47545956,  1.5925728 , -0.16132855, -0.55087949, -0.74461081,
         0.75291107,  0.14079864, -0.62072967, -1.94228905, -0.4836591 ,
         1.86750159, -0.22914788, -0.82065181],
       [-1.74679706, -0.10495034,  0.79657967, -0.55087949,  0.50147259,
        -1.5272218 , -0.84676261,  1.0456339 ,  0.51485643,  2.06757196,
        -0.53547478, -0.22914788, -0.82065181]])

In [ ]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, stratify=y, random_state=10)

Training a model using SVM later bagging

In [143]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

scores = cross_val_score(SVC(), X, y, cv=5)
scores.mean()

0.6906445672191528

**Use bagging now with SVM**

In [145]:
from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(estimator=SVC(), n_estimators=100, max_samples=0.8, random_state=20)
scores = cross_val_score(bag_model, X, y, cv=5)
scores.mean()

0.686206261510129

As you can see above, using bagging in case of SVM doesn't make much difference in terms of model accuracy. Bagging is effective when we have high variance and instable model such as decision tree. Let's explore how bagging changes the performance for a decision tree classifier.

#### Train a model using decision tree and then using bagging

In [146]:
from sklearn.tree import DecisionTreeClassifier

scores = cross_val_score(DecisionTreeClassifier(random_state=0), X, y, cv=5)
scores.mean()

0.7193984039287907

In [147]:
bag_model = BaggingClassifier(
                              estimator=DecisionTreeClassifier(random_state=0), 
                              n_estimators=100,
                              max_samples=0.9,
                              oob_score=True,
                              random_state=20
                              )

scores = cross_val_score(bag_model, X, y)
scores

array([0.84530387, 0.8121547 , 0.81111111, 0.8       , 0.72222222])

In [148]:
scores.mean()

0.798158379373849

**with bagging the score improved from 71.93% to 79.81%**

#### Train a model using Random Forest which itself uses bagging underneath

In [149]:
from sklearn.ensemble import RandomForestClassifier

scores = cross_val_score(RandomForestClassifier(), X, y, cv=5)
scores.mean()

0.8225721301411909

**Random forest gave even a better performance with 82.25% as score. Underneath it used bagging where it sampled not only data rows but also the columns (or features)**