<h1>XGBoost Cloud Prediction Invocation Template</h1>
<h4>Invoke SageMaker Prediction Service</h4>

In [3]:
pip install --no-cache-dir sagemaker

Requirement already satisfied: sagemaker in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (2.256.1)
Requirement already satisfied: attrs<26,>=24 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (25.4.0)
Requirement already satisfied: boto3<2.0,>=1.42.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (1.42.33)
Requirement already satisfied: cloudpickle>=2.2.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (3.1.2)
Requirement already satisfied: docker in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (7.1.0)
Requirement already satisfied: fastapi in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (0.128.0)
Requirement already satisfied: google-pasta in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (0.2.0)
Requirement already satisfied: importlib-metadata<7.0,>=1.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (6.11.0)
Requirement already satisfied: jsonschema in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (4.26.0)
Requirement already satisfied: numpy<3.0,>=1.26.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (1.26.4)
Requirement already satisfied: omegaconf<3,>=2.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (2.3.0)
Requirement already satisfied: packaging<25,>=23.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (24.2)
Requirement already satisfied: pandas>=2.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (2.3.3)
Requirement already satisfied: pathos in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (0.3.5)
Requirement already satisfied: platformdirs in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (4.5.1)
Requirement already satisfied: protobuf<6.32,>=3.12 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (6.31.1)
Requirement already satisfied: psutil in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (7.2.1)
Requirement already satisfied: PyYAML>=6.0.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (6.0.3)
Requirement already satisfied: requests in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (2.32.5)
Requirement already satisfied: sagemaker-core<2.0.0,>=1.0.71 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (1.0.74)
Requirement already satisfied: schema in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (0.7.8)
Requirement already satisfied: smdebug_rulesconfig==1.0.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (1.0.1)
Requirement already satisfied: tblib<4,>=1.7.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (3.2.2)
Requirement already satisfied: tqdm in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (4.67.1)
Requirement already satisfied: urllib3<3.0.0,>=1.26.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (2.6.3)
Requirement already satisfied: uvicorn in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (0.40.0)
Requirement already satisfied: graphene<4,>=3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker) (3.4.3)
Requirement already satisfied: botocore<1.43.0,>=1.42.33 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker) (1.42.33)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from botocore<1.43.0,>=1.42.33->boto3<2.0,>=1.42.2->sagemaker) (2.9.0.post0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker) (3.2.7)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker) (3.2.0)
Requirement already satisfied: typing-extensions<5,>=4.7.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker) (4.15.0)
Requirement already satisfied: zipp>=0.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from importlib-metadata<7.0,>=1.4.0->sagemaker) (3.23.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from omegaconf<3,>=2.2->sagemaker) (4.9.3)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.33->boto3<2.0,>=1.42.2->sagemaker) (1.17.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker) (2.9.2)
Requirement already satisfied: rich<15.0.0,>=13.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker) (14.2.0)
Requirement already satisfied: mock<5.0,>4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker) (4.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from jsonschema->sagemaker) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from jsonschema->sagemaker) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from jsonschema->sagemaker) (0.30.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker) (2.23.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker) (0.1.2)
Requirement already satisfied: pytz>=2020.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from pandas>=2.3.0->sagemaker) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from pandas>=2.3.0->sagemaker) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests->sagemaker) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests->sagemaker) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests->sagemaker) (2026.1.4)
Requirement already satisfied: starlette<0.51.0,>=0.40.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from fastapi->sagemaker) (0.50.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from fastapi->sagemaker) (0.0.4)
Requirement already satisfied: anyio<5,>=3.6.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from starlette<0.51.0,>=0.40.0->fastapi->sagemaker) (4.12.1)
Requirement already satisfied: ppft>=1.7.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from pathos->sagemaker) (1.7.8)
Requirement already satisfied: dill>=0.4.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from pathos->sagemaker) (0.4.1)
Requirement already satisfied: pox>=0.3.7 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from pathos->sagemaker) (0.3.7)
Requirement already satisfied: multiprocess>=0.70.19 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from pathos->sagemaker) (0.70.19)
Requirement already satisfied: click>=7.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from uvicorn->sagemaker) (8.3.1)
Requirement already satisfied: h11>=0.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from uvicorn->sagemaker) (0.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import os

import boto3
import re # python regex module
from sagemaker import get_execution_role
import sagemaker

# SDK 2 serializers and deserializers
from sagemaker.serializers import CSVSerializer
from sagemaker.deserializers import JSONDeserializer

In [23]:
# SDK 2
# RealTimePredictor renamed to Predictor
# https://sagemaker.readthedocs.io/en/stable/v2.html

# Create a predictor and point to an existing endpoint
endpoint_name = 'bikerental-endpoint'
predictor = sagemaker.predictor.Predictor(endpoint_name=endpoint_name)

In [24]:
predictor.serializer = CSVSerializer()

In [25]:
df_all = pd.read_csv('bike_test.csv')

In [26]:
df_all.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,year,month,day,dayofweek,hour
0,2011-01-20 00:00:00,1,0,1,1,10.66,11.365,56,26.0027,2011,1,20,3,0
1,2011-01-20 01:00:00,1,0,1,1,10.66,13.635,56,0.0000,2011,1,20,3,1
2,2011-01-20 02:00:00,1,0,1,1,10.66,13.635,56,0.0000,2011,1,20,3,2
3,2011-01-20 03:00:00,1,0,1,1,10.66,12.880,56,11.0014,2011,1,20,3,3
4,2011-01-20 04:00:00,1,0,1,1,10.66,12.880,56,11.0014,2011,1,20,3,4

In [27]:
df_all.columns[1:]

Index(['season', 'holiday', 'workingday', 'weather', 'temp', 'atemp',
       'humidity', 'windspeed', 'year', 'month', 'day', 'dayofweek', 'hour'],
      dtype='object')

In [28]:
# Need to pass an array to the prediction
# can pass a numpy array or a list of values [[19,1],[20,1]]
arr_test = df_all[df_all.columns[1:]].values

In [29]:
type(arr_test)

numpy.ndarray

In [30]:
arr_test.shape

(6493, 13)

In [31]:
arr_test[:5]

array([[1.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 1.06600e+01,
        1.13650e+01, 5.60000e+01, 2.60027e+01, 2.01100e+03, 1.00000e+00,
        2.00000e+01, 3.00000e+00, 0.00000e+00],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 1.06600e+01,
        1.36350e+01, 5.60000e+01, 0.00000e+00, 2.01100e+03, 1.00000e+00,
        2.00000e+01, 3.00000e+00, 1.00000e+00],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 1.06600e+01,
        1.36350e+01, 5.60000e+01, 0.00000e+00, 2.01100e+03, 1.00000e+00,
        2.00000e+01, 3.00000e+00, 2.00000e+00],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 1.06600e+01,
        1.28800e+01, 5.60000e+01, 1.10014e+01, 2.01100e+03, 1.00000e+00,
        2.00000e+01, 3.00000e+00, 3.00000e+00],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 1.06600e+01,
        1.28800e+01, 5.60000e+01, 1.10014e+01, 2.01100e+03, 1.00000e+00,
        2.00000e+01, 3.00000e+00, 4.00000e+00]])

In [32]:
result = predictor.predict(arr_test[:2])

In [33]:
result

b'2.332122325897217\n1.9005593061447144\n'

In [34]:
arr_test.shape

(6493, 13)

### Split the input data into chunks
There are thousands of rows in this data set for which need inference.  
When communicating over internet, it is a good idea to split the data into chunks to prevent payload and timeout error

In [35]:
# For large number of predictions, we can split the input data and
# Query the prediction service.
# array_split is convenient to specify how many splits are needed

# Splitting using regular expression as xgboost 1-2-2 is returning
# predicted values with inconsistent delimiters (comma, newline or both)

# pattern looks for one or more of non-numeric characters
pattern = r'[^0-9.]+'

predictions = []
for arr in np.array_split(arr_test,10):
    result = predictor.predict(arr)
    result = re.split(pattern,result.decode("utf-8"))

    print (arr.shape)
    predictions += [float(r) for r in result if r != ""] # Thanks, Ionut Barbu!

(650, 13)
(650, 13)
(650, 13)
(649, 13)
(649, 13)
(649, 13)
(649, 13)
(649, 13)
(649, 13)
(649, 13)

In [36]:
len(predictions)

6493

In [37]:
np.expm1(predictions)

array([  9.29977784,   5.68963495,   4.11209937, ..., 133.68598006,
        92.35797767,  52.00191752])

In [38]:
df_all['count'] = np.expm1(predictions)

In [39]:
df_all.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,year,month,day,dayofweek,hour,count
0,2011-01-20 00:00:00,1,0,1,1,10.66,11.365,56,26.0027,2011,1,20,3,0,9.299778
1,2011-01-20 01:00:00,1,0,1,1,10.66,13.635,56,0.0000,2011,1,20,3,1,5.689635
2,2011-01-20 02:00:00,1,0,1,1,10.66,13.635,56,0.0000,2011,1,20,3,2,4.112099
3,2011-01-20 03:00:00,1,0,1,1,10.66,12.880,56,11.0014,2011,1,20,3,3,1.822707
4,2011-01-20 04:00:00,1,0,1,1,10.66,12.880,56,11.0014,2011,1,20,3,4,1.604999

In [40]:
df_all[['datetime','count']].to_csv('predicted_count_cloud.csv',index=False)

In [41]:
# Delete Endpoint to prevent unnecessary charges
predictor.delete_endpoint()